### PR TITLE
fix problem of trying to get type of undefined

### PR DESCRIPTION
**Pull request by rafacianci**
# New

fix problem trying to access type of an undefined/null prop

# Testing

- [ ] Unit
- [ ] Integration
- [x] Localhost

# Screenshots

### CODE REVIEW

**Review by mresposito — APPROVED** [review]

**Comment by mresposito** [comment]
@prevwong can you merge back to master?

**Comment by prevwong** [comment]
@rafacianci @mresposito Oh a similar fix is already in the main repo (https://github.com/prevwong/craft.js/blob/develop/packages/core/src/utils/serializeNode.tsx#L23-L25) 

But we can add this in the fork too just in case. Rafa, could you follow the file on the main repo above to fix this problem?

**Comment by matdru** [comment]
Since we are phasing out the fork this wont be needed anymore, right ?

**Comment by matdru** [comment]
I'm closing this since this was solved and confirmed to be working on main repo

**Pull request closed without merging**
